#!/usr/bin/bash

set -euo pipefail

usage () {
	cat <<EOF_USAGE
Usage: git localmirror [COMMAND|URL]

    If no parameter used   : list all local repos
    URL                    : git mirror url to $localdir

COMMANDS:

    help          : this help
    update        : update all local mirror found in $localdir


EOF_USAGE
}


localdir="$HOME"/repositories/Public

if [ "$#" == 0 ]; then
	cd "$localdir"
	for d in $(find . -type d -name "*.git"); do
		printf -- "%s %s\n" "$(cat "$d"/description)" "${d//.git}"
	done
	exit $?
fi
url="$1"

case "$url" in
    "--help"|"-h"|"help")
		usage
		exit 0
		;;
	"themes")
	    cd "$localdir"
	    ls -1 | grep -vE '\.git|^\.$'
	    exit $?
		;;
	"update")
	    cd "$localdir"
		for d in $(find . -type d -name '*.git'); do
			printf -- "[*] updating %s : " "$d"
			( cd "$d" && git remote get-url origin && "$0" "$(git remote get-url origin)" )
		done
		exit $?
		;;
esac


if [ "$#" == "2" ];
then
    subdir="$localdir"/"$2"/"$(dirname "${url#*://}")"
else
    subdir="$localdir"/"$(dirname "${url#*://}")"
fi

reponame="${url##*/}"
localrepodir="$subdir"/"${reponame//.git}".git

[ -d "$subdir" ] || mkdir -p "$subdir"

if [ -d "$localrepodir" ]; then
	git --git-dir="$localrepodir" fetch origin
else
	git clone --mirror "$url" "$localrepodir"
fi

cd "$localrepodir"
# Update Description file in repo
lastcommitref="$(git for-each-ref --sort=-authordate --count=1 --format='%(refname)')"
git log --abbrev-commit --pretty=format:"%s" "$lastcommitref" -1 > "$localrepodir"/description
echo " - Cloned from : $url" >> "$localrepodir"/description

#
# Update agefile for cgit
#
agefile="$(git rev-parse --git-dir)"/info/web/last-modified
mkdir -p "$(dirname "$agefile")" &&
git for-each-ref \
        --sort=-authordate --count=1 \
        --format='%(authordate:iso8601)' \
        >"$agefile"
