volumes:
  mykdc:
    #external: false

services:
  init_volumes:
    image: kerberos:alpine
    restart: no
    entrypoint: /bin/sh
    command: -c 'mkdir -p /mnt/conf /mnt/db /mnt/keytabs'
    volumes:
      - type: volume
        source: mykdc
        target: /mnt

  kerberos:
    image: kerberos:alpine
    build:
      context: .
      dockerfile: Dockerfile-kdc
    ports:
      - "8888:88/tcp"
      - "8888:88/udp"
    depends_on:
      init_volumes:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: mykdc
        target: /var/krb5kdc
        volume:
          nocopy: true
          subpath: conf
      - type: volume
        source: mykdc
        target: /var/lib/krb5kdc
        volume:
          nocopy: true
          subpath: db
      - type: volume
        source: mykdc
        target: /srv/keytabs
        volume:
          nocopy: true
          subpath: keytabs

  check_keytab:
    image: alpine
    entrypoint: /bin/sh
    command: -c 'while :; do [ -f /srv/keytabs/http-localhost.keytab ] && exit 0; sleep 1; done'
    volumes_from:
      - kerberos:ro

  www:
    image: apache:keberos
    build:
      context: .
      dockerfile: Dockerfile-http
    command: -C 'serverName localhost'
    ports:
      - "8880:80/tcp"
    depends_on:
      check_keytab:
        condition: service_completed_successfully
    volumes:
      - type: volume
        source: mykdc
        target: /etc/apache2/keytabs
        volume:
          nocopy: true
          subpath: keytabs


